Added document about units
QENSlibrary/QENSmodels pull request #12
Opened 2020-07-13 18:10 UTC by celinedurniak

2020-07-20 11:02 UTC, TOFarmer requested changes
Looks good in general, I have suggested a few minor changes.

Also, I think we discussed having a table to summarise some of the common unit combinations, so that key information can be picked out easily - do we still want to do this or shall we leave it out?

2020-07-20 11:02 UTC, TOFarmer commented on docs/handling_units.rst
> +================================================
```suggestion
==================================================
```
The underline is too short

2020-07-20 11:02 UTC, TOFarmer commented on docs/handling_units.rst
> +units and the fitted data will be simply given in arbitrary units. In this case, the global scaling
```suggestion
units and the fitted data will simply be given in arbitrary units. In this case, the global scaling
```

2020-07-20 11:02 UTC, TOFarmer commented on docs/handling_units.rst
> +in absolute units, then this scaling factor will be given also in :math:`[E]^{-1}` units.
```suggestion
in absolute units, then this scaling factor will also be given in :math:`[E]^{-1}` units.
```

2020-07-20 11:02 UTC, TOFarmer commented on docs/handling_units.rst
> +this is given in |Ang^-1|, but it is not uncommon to use :math:`nm^{-1}`.
I could be wrong but I don't think units (in this case nm) should be italicised.  This also goes for a number of units below (e.g. THz, rad etc)

2020-07-20 11:02 UTC, TOFarmer commented on docs/handling_units.rst
> +:math:`[time]^{-1}` (:math:`[T]^{-1}`).
Personally I would say it is more common for time to be symbolised with a lowercase t rather than capital T.

2020-07-20 11:02 UTC, TOFarmer commented on docs/handling_units.rst
> +is given in |Ang^-1|, and :math:`\hbar\omega` is in |Ang^-1| and we are fitting a
The units of hbar omega should be meV.

2020-07-20 11:02 UTC, TOFarmer commented on docs/handling_units.rst
> +:math:`D = \Gamma/Q^2` and its units will be :math:`E.L^2` if the input data was
Can we use a central dot (I thik \cdot should work) for multiplication?  Otherwise the . symbol makes it appear to me that the sentence has ended.

2020-07-20 11:02 UTC, TOFarmer commented on docs/handling_units.rst
> +:math:`\omega=1.519.10^{12}\ rad/s`, giving [#f3]_ :
Using the same symbol (lower dot) for the decimal point and the multiplication of the exponent makes things a little hard to read.  We should at least use the center dot (personally I prefer x to denote multiplication in this context but I appreciate we may want to stick with cdot for consistency.)

2020-07-20 11:02 UTC, TOFarmer commented on docs/handling_units.rst
> +case, :math:`\langle u_x^2\rangle`is in units of :math:`L^2`, so typically the parameter returned
For some reason the section `is in units of :math:L^2` did not appear for me when I built the documentation in html - it might be worth someone else checking whether this is specific to me or more general.

2020-07-20 11:02 UTC, TOFarmer commented on docs/handling_units.rst
> +Adimensional parameters
I think maybe 'Dimensionless ' might be more commonly used than 'Adimensional', so I would suggest switching to this.

2020-07-20 11:02 UTC, TOFarmer commented on docs/handling_units.rst
> +Although they do not require any conversion, they are listed here for completeness.
```suggestion
Although they do not require any conversion, a few examples of dimensionless parameters are listed here:
```

2020-07-20 11:10 UTC, gonzalezma reviewed
Sorry, I started to do corrections to the rst file and then I committed it to the branch. Not sure that this is the best practice, but now it's done! In my commit, I corrected a couple of things, but I also did a large number of style changes concerning the multiplication dot and the style of the units (according to https://physics.nist.gov/cuu/Units/checklist.html, the unit symbols should be in Roman type). I've seen later that some of my changes address a few of Tom's comments, so perhaps you can use my commit as a new base to add the remaining comments from Tom that I did not address.

2020-07-21 08:38 UTC, celinedurniak commented on docs/handling_units.rst
> +Although they do not require any conversion, they are listed here for completeness.
I made the corrections.

2020-07-21 11:13 UTC, celinedurniak commented on docs/handling_units.rst
> +case, :math:`\langle u_x^2\rangle`is in units of :math:`L^2`, so typically the parameter returned
I had the same issue. It was due to a missing space.

2020-07-21 11:29 UTC, celinedurniak commented on docs/handling_units.rst
> +:math:`[time]^{-1}` (:math:`[T]^{-1}`).
I changed the symbol for time to lowercase

2020-07-21 12:09 UTC, celinedurniak commented
@TOFarmer  Miguel and I had implemented your suggestions.

2020-07-22 15:56 UTC, TOFarmer approved these changes
Looks good to me.  Do you want me to merge?

2020-07-22 16:37 UTC, celinedurniak commented
@TOFarmer You can merge the branch. Thanks.

2020-07-22 16:53 UTC, merged